### PR TITLE
Setting to customize the create_engine kwargs 

### PR DESCRIPTION
**Pull request by mb-a-roach**

### CODE REVIEW

**Comment by ryanhiebert** [comment]
@ticosax I'm not sure why he closed the other PR and opened this one, but this a cleaned up version of https://github.com/aldjemy/aldjemy/pull/249. I'm not seeing any alternative to meeting this use case.

**Review by ryanhiebert — CHANGES_REQUESTED** [review]
I agree that adding a test for this new functionality is needed. We don't want to accidentally break this feature for you or others in the future.

**Comment by ryanhiebert** [comment]
@ticosax I think it's safe to think he may not have opportunity for further follow-up on this. Is this something that we as maintainers think has enough value that we'd like to go ahead and complete it, or would we think it better abandon it? I don't have much of an opinion, but atm I also don't feel particularly motivated to write the tests it would need.

**Comment by ticosax** [comment]
same here :) Maybe the submitter business case has been abandoned.
@mb-a-roach happy to follow up on this one, if you still have incentives to make it happen. we are closing it for now.

**Pull request closed without merging**
