### PR TITLE
Attempt at fixing the legacy mapper registration

### LINKED ISSUE #192: sqlalchemy v2 deprecation (orm.mapper)
Heya, here's the offender:

```
  /opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/aldjemy/orm.py:152: RemovedIn20Warning: Calling the mapper() function directly outside of a declarative registry is deprecated. Please use the sqlalchemy.orm.registry.map_imperatively() function for a classical mapping. (Background on SQLAlchemy 2.0 at: sqlalche.me/e/b8d9)
    orm.mapper(sa_model, table, attrs)
```

Note to show these warnings, in `.github/workflows/build.yml` I would add to your test runs:

```yaml
      env:
        SQLALCHEMY_WARN_20: 1
```

(see https://docs.sqlalchemy.org/en/14/changelog/migration_20.html)

### PR DESCRIPTION
**Pull request by ticosax**
fixes #192

### CODE REVIEW

**Review by ryanhiebert — COMMENTED** [review]
I mean, it looks fine to me, if it works. Since you've titled it "attempt", what do you need to do to make it more than an attempt, to be confident that its an improvement? If it's not known to be an improvement, then its only risk, so I wouldn't want to merge that.

**Comment by ryanhiebert** [comment]
Also, thank you so much for digging into these issues!

**Comment by ticosax** [comment]
I don't fully understand what a mapper_registry is. It's as good as the test suite passing. And for what it's worth, it works within our project.
Knowing it's going to be a blocker for future support of SQLA 2.0, I'd say it's worth it.

**Review by ryanhiebert — APPROVED** [review]

**Comment by chrisjsewell** [comment]
Cheers!

**Pull request merged**
