### PR TITLE
Get rid of backward compatible code.

### PR DESCRIPTION
**Pull request by ticosax**
since we will support only python>=3.6, django=>2.2; we don't need those anymore.

I will rebase it once #100 is merged.

That's all I could see. Please let me know if you see more changes like this

### CODE REVIEW

**Comment by ryanhiebert** [comment]
I should have waited to release 1.0 until this was merged, since this is where the breaking changes actually are. Oh well. Depending when we get this one in, I may go ahead and release 2.0 at that point rather than potentially breaking things with a less clear signal to users.

**Comment by ticosax** [comment]
releasing it under a new major version sounds reasonable

**Comment by ryanhiebert** [comment]
Does this still need to rebased?

**Review by ryanhiebert — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
