### PR TITLE
_use_threadlocal unavailable in SQLAlchemy 1.4

### PR DESCRIPTION
**Pull request by mattrbianchi**
When upgrading a project, it came to my attention that the DjangoPool class is using a field that was removed from SQLAlchemy pools when SQLAlchemy went to 1.4. The code change can be found [here](https://github.com/sqlalchemy/sqlalchemy/commit/dfb20f07d8796ec27732df84c40b4ce4857fd83b#diff-7e2299f13e067d8133b1d0d2131e8a0898552cd8337767dfb981849cfb8822c6L172).

Unfortunately, my project is on Django 4.1 so I have done my best given the contributing instructions to apply the patch to 2.6 since Aldjemy 3.0 dropped support for Django < 4.2.

This should also be fine to include in 3.0, but I would really appreciate it if we could release a 2.6.1 along with it.

### CODE REVIEW

**Comment by ryanhiebert** [comment]
Thanks! It'll probably be a few days before I can get to merging this, but the changes seem reasonable to me. I'll give a backport release a shot. It sounds simple enough, but I've never done one before ;-).

**Comment by ryanhiebert** [comment]
I know that the backport is going to cause me some difficulty because I've recently changed the deployment process, but I'm hoping I can work it out.

**Comment by mattrbianchi** [comment]
Thanks for the quick response! Hopefully it's not too much trouble 😁 but if you hit a snag let me know.

**Comment by ryanhiebert** [comment]
I took a look at the CI work that I've done since then, and it's a lot. I'd rather cut a new release of the 3 line with the compatibility you need. Django 4.1 supported Python 3.8. I'd rather not add that back if nobody needs it. Would I be helping you enough if I just added Python 3.9+ support for Django 4.1?

**Comment by ryanhiebert** [comment]
I fixed this up to be based on the latest main. I intend to merge it in a couple hours.

**Comment by ryanhiebert** [comment]
Looks like I need to clean up some build stuff before I can merge.

While I'm doing that, can you help me know what problem you were seeing? How can I confirm that this is fixing an issue?

If we can write a test for it, even better, though this code is all very likely to be discarded in the next major version.

**Comment by mattrbianchi** [comment]
Hey Ryan, thanks again for looking at this so soon. Luckily, I'm on Python 3.9 so adding Django 4.1 back in works and then we can upgrade to 3+.

The error is: `AttributeError: 'DjangoPool' object has no attribute '_use_threadlocal'`. 

The specific problem I'm running into is in a test where we create a SQLAlchemy engine with a DjangoPool. But when .dispose() is called on the engine, [that eventually makes a call](https://github.com/sqlalchemy/sqlalchemy/blob/dfe401fd471323638ad3e1b1027d89e01fcbeef5/lib/sqlalchemy/engine/base.py#L3081) to `DjangoPool.recreate()`, which attempts to make a new DjangoPool passing `self._use_threadlocal`. This is where the error occurs since that field doesn't exist on SQLAlchemy Pools as of 1.4. 

As for testing, I scanned for a conventional test suite that I might be able to add a unit test to but missed the tests.py in the test_project folder. I'll see if I can write a test that reproduces the issue.

**Comment by ryanhiebert** [comment]
Awesome, thank you! I'll hold on merging this until you get around to doing that, especially since it seems like you already may have something pretty close to a test case elsewhere.

**Comment by ryanhiebert** [comment]
I guess the build failure must just be a fluke. Everything looks good now for the build, so as soon as we get a test, I'll get this merged. Thanks for looking into the issue you found!

**Comment by mattrbianchi** [comment]
Test added!

I made sure to undo the change to reveal the error via the test suite and this was the output:
```python
=================================================================================================== FAILURES ===================================================================================================
____________________________________________________________________________________ DjangoPoolTest.test_pool_can_recreate _____________________________________________________________________________________

self = <test_project.pg.tests.DjangoPoolTest testMethod=test_pool_can_recreate>

    def test_pool_can_recreate(self):
        """ Asserts DjangoPool can be created and recreate itself without throwing an exception """
        pool = DjangoPool("test_alias", creator=None)
>       new_pool = pool.recreate()

test_project/pg/tests.py:148:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <aldjemy.core.DjangoPool object at 0x107548ed0>

    def recreate(self):
        self.logger.info("Pool recreating")

        return DjangoPool(
            self.alias,
            self._creator,
            recycle=self._recycle,
            echo=self.echo,
            logging_name=self._orig_logging_name,
>           use_threadlocal=self._use_threadlocal,
        )
E       AttributeError: 'DjangoPool' object has no attribute '_use_threadlocal'

aldjemy/core.py:82: AttributeError
```

With the line removed, the test passes!

**Review by ryanhiebert — APPROVED** [review]

**Comment by ryanhiebert** [comment]
If the linters and tests are happy, I'll merge this.

**Comment by ryanhiebert** [comment]
I realized I missed fixing the version specifier to allow Django 4.1. That's cleaned up. I've released 3.2 with that change, so hopefully that's everything you asked for!

**Pull request merged**
