### PR TITLE
Reuse GHA Workflows and switch to poetry 1.1.12

### PR DESCRIPTION
**Pull request by ticosax**
For the sake of avoiding repetitions.

### CODE REVIEW

**Comment by ticosax** [comment]
@ryanhiebert I wonder why the CI is not triggered. Please, can you check the settings of the repo ? could be that build are not allowed for PR coming from forks ?

**Comment by ryanhiebert** [comment]
I'm not sure. The permissions seem reasonable. It allows from forks, but disallows from first-time contributors. Which you certainly are not.

**Comment by ryanhiebert** [comment]
Perhaps because this is a draft PR? I'm just making wild guesses, even with a draft PR I'd expect it to be running CI.

**Comment by ryanhiebert** [comment]
@ticosax My best guess as to what's going on is that whatever you're doing has caused these files to not be parsable or correct somehow, and it's just not doing anything because of that. I'm not sure what the issue is.

**Comment by ticosax** [comment]
Sorry, i didn't abandoned it. I was just away for few days. I will continue debugging it. Thanks for the pointer, I'll start there.

**Comment by ryanhiebert** [comment]
It's not a problem! You've been very helpful on the repository, and I appreciate any time that you're able to put into it. Your contributions are valuable and appreciated, and not required of you. Thank you for the work you do.

**Pull request closed without merging**
