### PR TITLE
Drop unmaintained versions of django and add support for 4.2

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by ryanhiebert** [comment]
The black conflicts are due to a newly released version of black. We should pick up the changes it wants. I'll get that cleaned up shortly.

**Comment by ticosax** [comment]
> The black conflicts are due to a newly released version of black. We should pick up the changes it wants. I'll get that cleaned up shortly.

Thanks, I will rebase

**Comment by ticosax** [comment]
after this one, I will try to see if we can support psycopg3 and psycogp2 at the same time.
I'm naively hoping it could put us closer to support sqlalchemy 2.0 .

**Comment by ryanhiebert** [comment]
That sounds fantastic, I'd love to support psycopg 3.

On this pull request, adding support for 4.2 is great, thank you for doing that. Removing support for 4.0 is also appropriate.

Removing support for 3.2 and 4.1 might be hasty still, since they are still in extended support, and keeping supported Django versions operable seems like a generally good policy. I'm usually pretty happy to loosen that slightly for LTS so that we can remove 3.2 at the same time as we remove for 4.1, as that's still given a normal release cycle of time to upgrade to the new LTS version, even though that's still a bit before extended support on that LTS release has finished.

If we wanted to have a more strict upgrade policy than just "whatever Django supports", then I think "current release and the previous" would be the next most reasonable option. It would be Django's support schedule, but without any deference to LTS releases. I'd be willing to do that if we can identify some utility in doing so, although the utility wouldn't need to necessarily be very big. For example, if continuing to support the previous LTS release caused some challenges to supporting psycopg 3, I wouldn't hesitate very long before being willing to drop it.

I'm not inclined to think we want to be more aggressive than even that without a really compelling reason. We want to make sure we're not forcing people to upgrade other packages at the same time as they upgrade ours. Upgrades are a lot safer to do when they don't require cascading upgrades.

**Comment by ticosax** [comment]
Sorry, I was confounded 2023 and 2024. I thought they reached EOL. I will change it of course.
Thanks

**Review by ryanhiebert — APPROVED** [review]
Sorry for dropping the ball on this one

**Comment by ticosax** [comment]
> Sorry for dropping the ball on this one

No worries. Everyone does it on its own time.

**Pull request merged**
