### PR TITLE
Remove sqlalchemy version freeze

### PR DESCRIPTION
**Pull request by Mogost**

### CODE REVIEW

**Comment by ryanhiebert** [comment]
Yeah, look like we're already getting some failed tests on PostgreSQL.

**Comment by Mogost** [comment]
```
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/sqlalchemy/orm/relationships.py:3463: SAWarning: relationship 'Group_permissions.permission' will copy column auth_permission.id to column auth_group_permissions.permission_id, which conflicts with relationship(s): 'Group.permissions' (copies auth_permission.id to auth_group_permissions.permission_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   The 'overlaps' parameter may be used to remove this warning. (Background on this error at: http://sqlalche.me/e/14/qzyx)
```
It seems to me that this problem is with ManyToMany releations here
https://github.com/aldjemy/aldjemy/blob/c2abcb8ceb02fb7d8c3f9d2e133633b6ba6afa46/aldjemy/orm.py#L78-L95

**Comment by ryanhiebert** [comment]
That sounds like a good place to go looking. I don't have any particular insight to give on that, I'm afraid.

**Review by ryanhiebert — APPROVED** [review]
Sweet! Great work!

**Comment by ryanhiebert** [comment]
Push the button to squash merge at your convenience, or I can if you prefer.

**Comment by Mogost** [comment]
@ryanhiebert This doesn't really fix the warnings and should be worked on separately. But the dropped tests were due to transactions in the tests.

**Comment by ryanhiebert** [comment]
Indeed. I appreciate getting the tests passing, and I'm glad that it didn't require changes to the library to get it working with 1.4. Hopefully we can figure out those warnings soon.

**Pull request merged**
