### PR TITLE
Remove support for deprecated python and django versions

### LINKED ISSUE #99: Are you fine with droping support for python2.7 ?
If yes I can contribute.

### PR DESCRIPTION
**Pull request by ticosax**
fixes #99

### CODE REVIEW

**Comment by ryanhiebert** [comment]
My preference is to not bother with tox for GitHub Actions. I'd rather just use each testing tool independently.

I'd like to wait a few more weeks before we merge this until Python 3.5 is also end-of-life and we can remove it from the build matrix. How does that sound to you? https://endoflife.date/python

**Comment by Mogost** [comment]
I think Python 3.5 should not be dropped before we no longer support django 2.2.

**Comment by ryanhiebert** [comment]
While I recognize that django 2.2 is still supported, and django 2.2 promises to not break with python 3.5 because it is LTS, I do not think we should do the same. I do not wish to have LTS releases of Aldjemy.

Those wishing to remain on an unsupported version of Python are free to also remain on an unsupported version of this library.

**Comment by ticosax** [comment]
> My preference is to not bother with tox for GitHub Actions. I'd rather just use each testing tool independently.
> 

The advantage of using tox during CI, is that we test tox.ini at the same time. It is maintained and updated.

> I'd like to wait a few more weeks before we merge this until Python 3.5 is also end-of-life and we can remove it from the build matrix. How does that sound to you? https://endoflife.date/python

Fine by me.

**Comment by ryanhiebert** [comment]
I'm inclined to get a new release out so that we can merge this pull request, including the dropping of Python 3.5 a bit early. Is there any work that we really want to get in the 0.11 release? The next release after it will be 1.0.

**Comment by ticosax** [comment]
From my point of view, master can be released as 0.11.
Thanks for coordinating it

**Review by ryanhiebert — APPROVED** [review]
There's a couple things that need to be cleaned up from this PR, but I'm going to do that in a followup PR.

**Pull request merged**
